---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shows
  template:
    metadata:
      labels:
        app: shows
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      containers:
        - name: shows
          image: ghcr.io/desecho/shows-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: shows
            - configMapRef:
                name: shows
          livenessProbe:
            httpGet:
              path: /health/
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: frontend
          image: ghcr.io/desecho/shows-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /health/
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
