# Generated by Django 5.2.12 on 2026-03-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showsapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="runtime",
        ),
    ]
