# Generated by Django 5.2.12 on 2026-03-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showsapp", "0002_remove_show_runtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
