# Generated by Django 5.2.12 on 2026-03-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showsapp", "0003_show_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="loaded_initial_data",
        ),
        migrations.RemoveField(
            model_name="user",
            name="only_for_friends",
        ),
    ]
